export {getComic, FETCH_COMIC_START, FETCH_COMIC_SUCCESS, FETCH_COMIC_FAILURE} from './comicActions';

export {getCurrentComic, FETCH_CURRENT_COMIC_START, FETCH_CURRENT_COMIC_SUCCESS, FETCH_CURRENT_COMIC_FAILURE} from './currentComicActions';

export {getNextComic, FETCH_NEXT_COMIC_START, FETCH_NEXT_COMIC_SUCCESS, FETCH_NEXT_COMIC_FAILURE} from './nextComicActions';